### ISSUE TITLE
리뷰 목록을 불러오는 과정에서 발생하는 ReviewVO 관련 에러

### ISSUE THREAD

**Issue by jhj010311** [Hongg7/charge_station#61]
-- 컨트롤러(ChargersController)
@RequestMapping("chargers/getSearchListForChargers")
	@ResponseBody
	public Map<String, Object> getReviews(@RequestParam("type") String type, @RequestParam("r_statId") String r_statId) throws Exception {
		ReviewVO reviewVO = new ReviewVO();
		reviewVO.setType(type);
		reviewVO.setR_statid(r_statId);
		
		List<ReviewVO> list = reviewService.getSearchListForChargers(reviewVO);
		
		Map<String, Object> result = new HashMap<>();
		result.put("reviewList", list);

		return result;
	}

-- 서비스(ReviewService)
public List<ReviewVO> getSearchListForChargers(ReviewVO reviewVO) throws Exception {
		return reviewDAO.selectSearchListForChargers(reviewVO);
	}

-- ReviewDAO
public List<ReviewVO> selectSearchListForChargers(ReviewVO reviewVo) throws Exception {
		return my.selectList("review.searchReviewListForChargers", reviewVo);
	}

-- reviewMapper
<select id="searchReviewListForChargers"
		parameterType="reviewVO" resultType="reviewVO">
		SELECT * FROM ( SELECT ROW_NUMBER()
		OVER(ORDER BY
		<if test="type.equals('like')">
			r_like DESC,
		</if>
		r_num DESC) as r_no,
		r_num,
		r_title, r_statid, r_content, r_writer, r_like, r_time, r_rank
		FROM
		review_board
		where r_statid = #{reviewVO.r_statid}
		) r2
		WHERE r2.r_no BETWEEN 1 AND 5 AND
		r2.r_num IS NOT NULL
	</select>

-- 에러코드
심각: 경로 [/tayotayo]의 컨텍스트 내의 서블릿 [appServlet]을(를) 위한 Servlet.service() 호출이, 근본 원인(root cause)과 함께, 예외 [Request processing failed; nested exception is org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.reflection.ReflectionException: There is no getter for property named 'reviewVO' in 'class com.multi.tayotayo.review.ReviewVO']을(를) 발생시켰습니다.
org.apache.ibatis.reflection.ReflectionException: There is no getter for property named 'reviewVO' in 'class com.multi.tayotayo.review.ReviewVO'
	at org.apache.ibatis.reflection.Reflector.getGetInvoker(Reflector.java:409)
	at org.apache.ibatis.reflection.MetaClass.getGetInvoker(MetaClass.java:164)
	at org.apache.ibatis.reflection.wrapper.BeanWrapper.getBeanProperty(BeanWrapper.java:162)
	at org.apache.ibatis.reflection.wrapper.BeanWrapper.get(BeanWrapper.java:49)
	at org.apache.ibatis.reflection.MetaObject.getValue(MetaObject.java:122)
	at org.apache.ibatis.reflection.MetaObject.metaObjectForProperty(MetaObject.java:145)
	at org.apache.ibatis.reflection.MetaObject.getValue(MetaObject.java:115)
	at org.apache.ibatis.executor.BaseExecutor.createCacheKey(BaseExecutor.java:220)
	at org.apache.ibatis.executor.CachingExecutor.createCacheKey(CachingExecutor.java:146)
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:82)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:148)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:433)
	at com.sun.proxy.$Proxy7.selectList(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.selectList(SqlSessionTemplate.java:230)
	at com.multi.tayotayo.review.ReviewDAO.selectSearchListForChargers(ReviewDAO.java:101)
	at com.multi.tayotayo.review.ReviewService.getSearchListForChargers(ReviewService.java:152)
	at com.multi.tayotayo.chargers.ChargersController.getReviews(ChargersController.java:97)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:209)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:871)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:777)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:991)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:925)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:978)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:870)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:489)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:855)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:583)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:212)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:156)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:181)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:156)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:181)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:156)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:168)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:483)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:679)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:617)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:934)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1698)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Unknown Source)

**Comment by jhj010311** [comment]
ReviewVO 객체에 대해서, getReviewVO에 해당하는 메서드를 실행시킨 적이 없는데,
getReviewVO를 실행했는데 그런 메서드는 존재하지 않는다고 하며 에러가 발생하는 중

**Comment by jhj010311** [comment]
syso를 통해 어디에서 에러가 발생하는지 체크를 시도

페이지 - 컨트롤러 - 서비스 - dao 전부 진입은 됐음
아마도 마지막 dao return의 단계에서 문제가 발생하는 모양

**Comment by jhj010311** [comment]
즉시 결과를 리턴하던 구조를 조금 고쳐서
리턴용 객체를 먼저 생성한 후, 생성 뒤에 syso를 통해서 한 번 더 체크하고 리턴하는 구조로 변경

새롭게 추가된 syso는 어느 것도 실행되지 않았으므로
dao에서 문제가 발생한 것이 확실해보임

**Comment by jhj010311** [comment]
mapper의 where r_statid = #{reviewVO.r_statid} 구문이 문제

reviewVO.r_statid를 r_statid로만 바꾸니 문제가 해결됨

**Comment by jhj010311** [comment]
확인 결과 매퍼 내 다른 구문들에도 비슷한 것이 있었으므로 담당하신 분에게 전달하기로 결정
